name: CI

on:
  push:
    branches: [ main, web_refactorred_new_filestyle ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install pytest pytest-cov ruff
          poetry config virtualenvs.create false && poetry install --no-root
      - name: Migrations
        env:
          DB_URL_MIGRATIONS: postgresql://test:test@localhost:5432/test_db
        run: |
          set -euo pipefail
          poetry run yoyo apply --batch --database "${DB_URL_MIGRATIONS:?DB_URL_MIGRATIONS is missing}" migrations

         
      
      - name: Linter
      
        run: |
          ruff check .
      

      - name: Run tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
        run: |
          pytest --cov=app --cov-report=term
